### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by diheinsohn** [mvines/sainsmart-relay16#6]
First of all i want to thank you very much for this coding. Makes it a lot easier than SainSmarts assistance. Well i was using the code and get to the instance that if a temperature was beneath a threshold it commands to power off the relay (ex. ./cli.js off 0). But in the iteration of sensing the temperature again, if it's beneath this threshold again, the same command (off 0) is turning on the relay. 

Do you know a way to fix this problem? or is there a way/command to check the relay statuses? 

ty

**Comment by diheinsohn** [comment]
fixed! i could fix it in your repo with your permission.

**Comment by mvines** [comment]
Oh cool! Please send a pull request

**Comment by diheinsohn** [comment]
I'm not sure how to do it. new to git. could you explain me a little bit more?. How do i choose the file that i modified in my repo to copy it in yours.

**Comment by mvines** [comment]
Sure, there are many existing tutorials about using github pull requests.  Here's one I found that seems decent: https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github

**Comment by diheinsohn** [comment]
K, i think i got it right.

**Comment by mvines** [comment]
Fixed at #8
